NewKarma/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using NewKarma.Models.Domain;
using NewKarma.Repository.UOW;
using ReflectionIT.Mvc.Paging;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NewKarma.Areas.Admin.Controllers
{
    public class BrandController : BaseController
    {
        private readonly IUnitOfWork _unit;
        public BrandController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        [HttpGet, DisplayName("مدیریت برند"), Authorize]
        public async Task<IActionResult> Index(int page = 1, int row = 15)
        {
            var brand = _unit.BaseRepo<Brand>().FindAllAsync();
            var PagingModel = PagingList.Create(await brand, row, page);
            List<int> Rows = new List<int>
            {
                5,10,15,20,50,100
            };

            ViewBag.RowID = new SelectList(Rows, row);
            ViewBag.NumOfRow = (page - 1) * row + 1;
            PagingModel.RouteValue = new RouteValueDictionary
            {
                {"row",row},
            };
            return View(PagingModel ?? null);
        }
        [HttpGet, DisplayName("افزودن برند"), Authorize]
        public IActionResult Create() { return View(); }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Brand model,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\imgUpload\\Brand\\");
                    string TempImage = filePath + "Original\\" + fileName;
                    using (var fileStream = new FileStream(TempImage, FileMode.Create))
                    {
                        await image.CopyToAsync(fileStream);
                    }
                    Image_resize(TempImage, filePath + fileName, 50);
                    string destination = filePath + "_" + fileName;
                    System.IO.File.Move(TempImage, destination);
                    if (System.IO.File.Exists(destination))
                        System.IO.File.Delete(destination);

                    Brand brand = new Brand
                    {
                        Logo = fileName,
                        Title = model.Title,
                        UserIDFK = model.UserIDFK,
                    };
                    await _unit.BaseRepo<Brand>().Create(brand);
                    await _unit.Commit();
                }
                else
                {
                    await _unit.BaseRepo<Brand>().Create(model);
                    await _unit.Commit();
                }
                return RedirectToAction(nameof(Index));//Hack:Is It Working I Mean Redirect to aciton
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet, DisplayName("ویرایش برند"), Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var brand = await _unit.BaseRepo<Brand>().FindByIdAsync(id);
            if (brand == null)
            {
                return null;
            }
            ViewBag.BrandId = new SelectList(_unit.BaseRepo<Brand>().FindAll());
            return View(brand);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Brand model ,IFormFile image)
        {
            if (id != model.BrandId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    Brand brandOld = _unit.BaseRepo<Brand>().FindByIdAsync(model.BrandId).Result;
                    if (brandOld != null)
                    {
                        brandOld.Title = model.Title;
                        brandOld.UserIDFK = model.UserIDFK;
                        var oldImage = _unit.BaseRepo<Brand>().FindByIdAsync(model.BrandId).Result.Logo;
                        if (oldImage==null)
                        {
                            if (image != null && image.Length > 0)
                            {
                                var fileName = Path.GetFileName(image.FileName);
                                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\imgUpload\\Brand\\");
                                string TempImage = filePath + "Original\\" + fileName;
                                using (var fileStream = new FileStream(TempImage, FileMode.Create))
                                {
                                    await image.CopyToAsync(fileStream);
                                }
                                brandOld.Logo = fileName;
                                Image_resize(TempImage, filePath + fileName, 50);
                                string destination = filePath + "_" + fileName;
                                System.IO.File.Move(TempImage, destination);
                                if (System.IO.File.Exists(destination))
                                    System.IO.File.Delete(destination);
                            }
                        }
                        else
                        {
                            var oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\imgUpload\\Brand", oldImage);
                            if (System.IO.File.Exists(oldPath))
                            {
                                if (image != null && image.Length > 0)
                                {
                                    System.IO.File.Delete(oldPath);
                                    var fileName = Path.GetFileName(image.FileName);
                                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\imgUpload\\Brand\\");
                                    string TempImage = filePath + "Original\\" + fileName;
                                    using (var fileStream = new FileStream(TempImage, FileMode.Create))
                                    {
                                        await image.CopyToAsync(fileStream);
                                    }
                                    brandOld.Logo = fileName;
                                    Image_resize(TempImage, filePath + fileName, 50);
                                    string destination = filePath + "_" + fileName;
                                    System.IO.File.Move(TempImage, destination);
                                    if (System.IO.File.Exists(destination))
                                        System.IO.File.Delete(destination);
                                }
                            }
                        }
                    }
                    _unit.BaseRepo<Brand>().Update(brandOld);
                    await _unit.Commit();
                    ViewBag.MsgConfirm = "ذخیره تغییرات با موفقیت انجام شد";
                    return View(model);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExist(model.BrandId))
                    {
                        ViewBag.MsgFailed = "خطا برند مورد نظر پیدا نشد";
                        return NotFound();
                    }
                    else
                    {
                        ViewBag.MsgFailed = "در ذخیره تغییرات خطایی رخ داده است.";
                        return View(model);
                    }
                }
            }
            else
            {
                ViewBag.MsgFaild = "اطلاعات فرم نا معتبر است.";
                return View(model);
            }
        }

        [HttpGet, DisplayName("حذف برند"), Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var brand = await _unit.BaseRepo<Brand>().FindByIdAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmred(int id)
        {
            var brand = await _unit.BaseRepo<Brand>().FindByIdAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            else
            {
                //cannot remove logo becase is null when the image was not uploaded and i think in brand model logo is null becase that upload with default image
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\imgUpload\\brand\\", brand.Logo);
                System.IO.File.Delete(filePath);
                _unit.BaseRepo<Brand>().Delete(brand);
                await _unit.Commit();
                return RedirectToAction(nameof(Index));
            }
        }


        //Hack:CHeck And Remove If Its Not Zaruri!
        public bool BrandExist(int id)
        {
            return _unit._context.Brands.Any(a => a.BrandId == id);
        }

        private void Image_resize(string inputImagePath, string outputImagePath, int newWidth)
        {
            const long quality = 50L;
            Bitmap source_Bitmap = new Bitmap(inputImagePath);
            double dblWidth_origial = source_Bitmap.Width;

NewKarma/Areas/Admin/Controllers/CarsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using NewKarma.Models.Domain;
using NewKarma.Models.View;
using NewKarma.Repository.UOW;
using ReflectionIT.Mvc.Paging;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace NewKarma.Areas.Admin.Controllers
{
    public class CarsController : BaseController
    {
        private readonly IUnitOfWork _unit;
        public CarsController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        [HttpGet, DisplayName("مدیریت خوردو"), Authorize]
        public async Task<IActionResult> Index(int page = 1, int row = 15)
        {
            var car = _unit.BaseRepo<Car>().FindAllAsync();
            List<int> Rows = new List<int>
            {
                5,10,15,20,50,100
            };

            ViewBag.RowID = new SelectList(Rows, row);
            ViewBag.NumOfRow = (page - 1) * row + 1;
            var PagingModel = PagingList.Create(await car, row, page);

            PagingModel.RouteValue = new RouteValueDictionary
            {
                {"row",row},
            };
            return View(PagingModel ?? null);
        }

        [HttpGet, DisplayName("افزودن خودرو"), Authorize]
        public IActionResult Create() { return View(); }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car model)
        {
            if (ModelState.IsValid)
            {
                await _unit.BaseRepo<Car>().Create(model);
                await _unit.Commit();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet, DisplayName("ویرایش خودرو"), Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _unit.BaseRepo<Car>().FindByIdAsync(id);
            if (car == null)
            {
                return null;
            }
            ViewBag.CarId = new SelectList(_unit.BaseRepo<Car>().FindAll());
            return View(car);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car model)
        {
            if (id != model.CarId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _unit.BaseRepo<Car>().Update(model);
                    await _unit.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExist(model.CarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet, DisplayName("حذف خودرو"), Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _unit.BaseRepo<Car>().FindByIdAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmred(int id)
        {
            var car = await _unit.BaseRepo<Car>().FindByIdAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            else
            {
                _unit.BaseRepo<Car>().Delete(car);
                await _unit.Commit();
                return RedirectToAction(nameof(Index));
            }
        }

        public bool CarExist(int id)
        {
            return _unit._context.Cars.Any(a => a.CarId == id);
        }
    }
}

NewKarma/Areas/Admin/Views/Shared/AdminLayout.cshtml
@inject NewKarma.Tools.ConvertDate convertDate
@inject Microsoft.AspNetCore.Identity.SignInManager<NewKarma.Areas.Identity.Data.ApplicationUser> signManager
<!doctype html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>KarmaYadak Admin</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/Admin/css/jquery-confirm.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="~/Admin/css/styles.css">
    <link rel="stylesheet" href="~/Admin/vendor/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="~/Admin/vendor/font-awesome/css/fontawesome-all.min.css">
    <link rel="sty  lesheet" href="~/Admin/css/jquery.bonsai.css">
    <link href="~/Admin/select2/dist/css/select2.css" rel="stylesheet" />
    <link href="~/Admin/css/bootstrap-fileinput.css" rel="stylesheet" />
    <link href="~/Admin/css/TreeView.css" rel="stylesheet" />
    <link href="~/Admin/css/comboTreePlugin.css" rel="stylesheet" />

</head>
<body class="sidebar-fixed header-fixed">
    <div class="page-wrapper">
        <nav class="navbar page-header">
            <div>
                <a href="#" class="btn btn-link sidebar-mobile-toggle d-md-none mr-auto">
                    <i class="fa fa-bars"></i>
                </a>
                <a class="navbar-brand" href="#">
                    <img src="~/img/logo.png" alt="logo" height="45">
                    پنل مدیریت کارما یدک
                </a>
                <a href="#" class="btn btn-link sidebar-toggle d-md-down-none">
                    <i class="fa fa-bars"></i>
                </a>
            </div>

            <ul class="navbar-nav ml-auto">
                <li>
                    <span>@convertDate.ConvertMiladiToShamsi(DateTime.Now, "dddd d MMMM yyyy")</span>
                </li>
                <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="~/Admin/images/avatar-1.png" class="avatar avatar-sm" alt="logo">
                                <span class="small ml-1 d-md-down-none">
                                    @signManager.UserManager.GetUserName(User)
                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="dropdown-header">حساب کاربری</div>
                                <a href="#" class="dropdown-item">
                                    <i class="fa fa-user"></i> پروفایل
                                </a> 
                                <a href="#" class="dropdown-item">
                                    <i class="fa fa-gem"></i> تنظیمات
                                </a>
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" value="Logout" class="dropdown-item">
                                        <i class="fa fa-lock"></i> خروج
                                    </button>
                                </form>
                            </div>
                </li>
            </ul>
        </nav>
        <div class="main-container">
            <partial name="_SideBar" />
            <div class="content">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/Admin/vendor/chart.js/chart.js"></script>
    <script src="~/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Admin/vendor/popper.js/popper.min.js"></script>
    <script src="~/Admin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Admin/js/jquery-confirm.min.js"></script>



    <script src="~/Admin/js/carbon.js"></script>
    <script src="~/Admin/js/demo.js"></script>
    <script src="~/Admin/select2/dist/js/select2.min.js"></script>
    <script src="~/Admin/select2/dist/js/select2.full.js"></script>
    <script src="~/Admin/js/bootstrap-fileinput.js"></script>
    <script src="~/Admin/js/TreeView.js"></script>
    <script src="~/Admin/js/comboTreePlugin.js"></script>
    <script src="~/Admin/js/icontains.js"></script>

    <script>

        // for select2
        $(".select2").select2({
            placeholder: "انتخاب کنید"
        });

        // for TreeView
        $('.demo1').bonsai();

    </script>
    @RenderSection("Scripts", false)
</body>
</html>

NewKarma/Areas/Admin/Views/Shared/_SideBar.cshtml
@addTagHelper*,NewKarma
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-title">پنل مدیریت</li>
            <li class="nav-item">
                <a asp-area="Admin" asp-controller="Dashbord" asp-action="Index" class="nav-link">
                    <i class="icon icon-speedometer"></i> داشبورد
                </a>
            </li>
            <li class="nav-item nav-dropdown">
                <a href="#" class="nav-link nav-dropdown-toggle">
                    <i class="icon icon-settings"></i> مدیریت قطعات <i class="fa fa-caret-left"></i>
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-link">
                            <i class="icon icon-eye"></i> مشاهده قطعات
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Product" asp-action="Create" class="nav-link">
                            <i class="icon icon-magnifier-add"></i> افزودن قطعه جدید
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a href="#" class="nav-link nav-dropdown-toggle">
                    <i class="icon icon-chart"></i>مدیریت دسته بندی <i class="fa fa-caret-left"></i>
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link">
                            <i class="icon icon-eye"></i> مشاهده دسته بندی
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Category" asp-action="Create" class="nav-link">
                            <i class="icon icon-pie-chart"></i> افزودن دسته بندی جدید
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a href="#" class="nav-link nav-dropdown-toggle">
                    <i class="icon icon-user"></i> مدیریت برند <i class="fa fa-caret-left"></i>
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Brand" asp-action="Index" class="nav-link">
                            <i class="icon icon-pin"></i> مشاهده برند ها
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Brand" asp-action="Create" class="nav-link">
                            <i class="icon icon-location-pin"></i> افزودن برند جدید
                        </a>
                    </li>
                </ul>
            </li>


            <li class="nav-item nav-dropdown">
                <a href="#" class="nav-link nav-dropdown-toggle">
                    <i class="icon icon-vector"></i> مدیریت خودرو ها <i class="fa fa-caret-left"></i>
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Cars" asp-action="Index" class="nav-link">
                            <i class="icon icon-action-undo"></i> مدیریت خودرو ها
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Admin" asp-controller="Cars" asp-action="Create" class="nav-link">
                            <i class="icon icon-action-redo"></i> افزودن خودرو ها
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</div>